import { test, expect } from '../../src/fixtures/test-fixtures';
import boundaryValues from '../../test-data/boundary-values.json';
import mockCatalog from '../../test-data/mock-products-100.json';
import {
  mockProductsCatalog,
  skipUnlessCatalogIsNetworked,
} from '../../src/utils/api-mock.util';
import { Product } from '../../src/types/product.types';
import { parseCurrency } from '../../src/utils/currency.util';

/**
 * The 100-product payload is committed static test data
 * (test-data/mock-products-100.json, regenerated by
 * scripts/generate-mock-products.mjs) rather than a runtime-built fixture.
 */
const largeCatalog = mockCatalog.products as Product[];

test.describe('Performance — Large catalog render', () => {
  test.beforeEach(() => skipUnlessCatalogIsNetworked());

  test('TC-PERF-001: 100 mocked products render without page errors', async ({
    page,
    productsPage,
  }) => {
    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await mockProductsCatalog(page, largeCatalog);
    await productsPage.gotoProducts();

    await expect
      .poll(async () => productsPage.addToCartButton.count(), {
        timeout: boundaryValues.interactiveTimeoutMs,
      })
      .toBe(largeCatalog.length);

    expect(await productsPage.getProductCountFromLabel()).toBe(largeCatalog.length);
    expect(pageErrors).toHaveLength(0);
  });

  test('TC-PERF-002: the first product stays interactive within the time budget', async ({
    page,
    productsPage,
    cart,
  }) => {
    await mockProductsCatalog(page, largeCatalog);
    await productsPage.gotoProducts();

    const startedAt = Date.now();
    const firstAddButton = productsPage.addToCartButton.first();
    await expect(firstAddButton).toBeEnabled({
      timeout: boundaryValues.interactiveTimeoutMs,
    });
    await firstAddButton.click();
    await expect(cart.cartHeader).toBeVisible();
    const elapsed = Date.now() - startedAt;

    // 15s budget: the app renders all 100 cards eagerly with no virtualisation,
    // so this guards against a regression that makes first interaction slower.
    expect(elapsed).toBeLessThan(boundaryValues.interactiveTimeoutMs);
    expect(await cart.getTotalQuantity()).toBe(1);
  });

  test('TC-PERF-003: every one of the 100 cards renders a title and a parsable price', async ({
    page,
    productsPage,
  }) => {
    await mockProductsCatalog(page, largeCatalog);
    await productsPage.gotoProducts();

    await expect
      .poll(async () => productsPage.productCard.count(), {
        timeout: boundaryValues.interactiveTimeoutMs,
      })
      .toBe(largeCatalog.length);

    const rendered = await productsPage.getAllCatalogProducts();
    expect(rendered).toHaveLength(largeCatalog.length);

    for (const product of rendered) {
      expect(product.title.length).toBeGreaterThan(0);
      expect(Number.isNaN(parseCurrency(product.priceText))).toBe(false);
    }
  });

  test('TC-PERF-004: filtering a 100-product catalog stays within the time budget', async ({
    page,
    productsPage,
    filter,
  }) => {
    const expectedAfterFilter = largeCatalog.filter((p) =>
      p.availableSizes.includes('M')
    ).length;
    expect(expectedAfterFilter).toBeGreaterThan(0);

    await mockProductsCatalog(page, largeCatalog);
    await productsPage.gotoProducts();

    const startedAt = Date.now();
    await filter.toggleSize('M');
    await expect
      .poll(async () => productsPage.getProductCountFromLabel(), {
        timeout: boundaryValues.interactiveTimeoutMs,
      })
      .toBe(expectedAfterFilter);
    const elapsed = Date.now() - startedAt;

    expect(elapsed).toBeLessThan(boundaryValues.interactiveTimeoutMs);
  });
});
